version: '3'

networks:
  internet_monitoring: {}

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention=200h"
    networks:
      - internet_monitoring
    volumes:
      - prometheus_data:/prometheus
      - ./configuration/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      - internet_monitoring
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000